#!/usr/bin/env bash

docker_args=(
  run -it --rm
  # required: app mount
  -v ".:/var/www"
  # optional: docker socket mount (to run app docker commands)
  -v "/var/run/docker.sock:/var/run/docker.sock"
  # optional: workspace (default if unset is 'workspace')
  -w /var/www
  # optional: docker network access (dbhub mcp, etc.)
  --network {YOUR_PROJECT_DOCKER_NETWORK}
  # required: image name
  claude-tools
)

docker "${docker_args[@]}" npx claude "$@"
